# Generated by Django 4.2.7 on 2025-06-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_access_token',
            field=models.TextField(blank=True, verbose_name='Token de Acesso Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Avatar Hash do Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_data_vinculacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Vinculação Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome de Exibição do Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_refresh_token',
            field=models.TextField(blank=True, verbose_name='Token de Refresh Discord'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID do Discord'),
        ),
    ]
