# Generated by Django 5.2.4 on 2025-07-12 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_sistema_cidadania_completo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicostatuscidadania",
            name="solicitacao",
        ),
        migrations.RemoveField(
            model_name="historicostatuscidadania",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="DocumentoCidadania",
        ),
        migrations.DeleteModel(
            name="HistoricoStatusCidadania",
        ),
    ]
