# Generated by Django 4.2.7 on 2025-06-16 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='anuncios/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link (Opcional)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['ordem', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BotaoConfiguravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(help_text='Ex: fas fa-user, bi bi-house, etc.', max_length=50, verbose_name='Classe do Ícone')),
                ('link', models.URLField(verbose_name='Link de Redirecionamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('cor_fundo', models.CharField(default='#007bff', max_length=7, verbose_name='Cor de Fundo (Hex)')),
            ],
            options={
                'verbose_name': 'Botão Configurável',
                'verbose_name_plural': 'Botões Configuráveis',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='GovBR Roleplay', max_length=100, verbose_name='Nome do Site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracao/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuracao/', verbose_name='Favicon')),
                ('link_discord', models.URLField(blank=True, null=True, verbose_name='Link do Discord')),
                ('mensagem_discord', models.CharField(default='Junte-se ao nosso Discord!', max_length=200, verbose_name='Mensagem do Discord')),
                ('rodape_texto', models.TextField(blank=True, null=True, verbose_name='Texto do Rodapé')),
                ('cor_primaria', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor Primária (Hex)')),
                ('cor_secundaria', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundária (Hex)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='EstatisticaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usuarios', models.PositiveIntegerField(default=0, verbose_name='Total de Usuários')),
                ('total_imigrantes', models.PositiveIntegerField(default=0, verbose_name='Total de Imigrantes')),
                ('total_cidadaos', models.PositiveIntegerField(default=0, verbose_name='Total de Cidadãos')),
                ('usuarios_ultimos_7_dias', models.PositiveIntegerField(default=0, verbose_name='Usuários Últimos 7 Dias')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estatística do Sistema',
                'verbose_name_plural': 'Estatísticas do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(max_length=300, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem')),
                ('tipo', models.CharField(choices=[('governo', 'Notícia do Governo'), ('imprensa', 'Notícia da Imprensa')], default='governo', max_length=10, verbose_name='Tipo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque no Slide')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao', '-data_criacao'],
            },
        ),
    ]
