# Generated by Django 4.2.7 on 2025-06-17 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20250616_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cargo')),
                ('simbolo_gestao', models.CharField(choices=[('**', '** (Chefe de Poder)'), ('*', '* (Líder de Órgão)'), ('+', '+ (Chefe de Entidade)'), ('nenhum', 'Nenhum')], default='nenhum', max_length=10, verbose_name='Símbolo de Gestão')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['entidade__orgao__poder__nome', 'entidade__orgao__nome', 'entidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Poder')),
            ],
            options={
                'verbose_name': 'Poder',
                'verbose_name_plural': 'Poderes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cargo', verbose_name='Cargo Atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Órgão')),
                ('poder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poder', verbose_name='Poder')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['poder__nome', 'nome'],
                'unique_together': {('nome', 'poder')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargo', verbose_name='Cargo')),
                ('exonerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exoneracoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Exonerado Por')),
                ('nomeado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomeacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Nomeado Por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Cargo',
                'verbose_name_plural': 'Histórico de Cargos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Entidade')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['orgao__poder__nome', 'orgao__nome', 'nome'],
                'unique_together': {('nome', 'orgao')},
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entidade', verbose_name='Entidade'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('nome', 'entidade')},
        ),
    ]
