# Generated by Django 4.2.7 on 2025-06-17 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_cargo_poder_profile_orgao_historicocargo_entidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número sequencial da edição', unique=True)),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now)),
                ('ano', models.PositiveIntegerField(default=2025)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diário Oficial',
                'verbose_name_plural': 'Diários Oficiais',
                'ordering': ['-data_publicacao', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='historicocargo',
            name='publicado_diario',
            field=models.BooleanField(default=False, help_text='Se já foi publicado no Diário Oficial'),
        ),
        migrations.CreateModel(
            name='PublicacaoDiarioOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nomeacao', 'Nomeação'), ('exoneracao', 'Exoneração'), ('transferencia', 'Transferência'), ('promocao', 'Promoção'), ('decreto', 'Decreto'), ('portaria', 'Portaria'), ('edital', 'Edital'), ('aviso', 'Aviso')], max_length=20)),
                ('secao', models.CharField(choices=[('executivo', 'Poder Executivo'), ('legislativo', 'Poder Legislativo'), ('judiciario', 'Poder Judiciário')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('automatica', models.BooleanField(default=False, help_text='Se a publicação foi gerada automaticamente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='main.diariooficial')),
                ('historico_cargo', models.ForeignKey(blank=True, help_text='Histórico de cargo relacionado (para publicações automáticas)', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.historicocargo')),
            ],
            options={
                'verbose_name': 'Publicação do Diário Oficial',
                'verbose_name_plural': 'Publicações do Diário Oficial',
                'ordering': ['tipo', 'criado_em'],
            },
        ),
    ]
