# Generated by Django 4.2.7 on 2025-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_diariooficial_historicocargo_publicado_diario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDiarioOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_esquerda', models.ImageField(blank=True, help_text='Imagem que aparece no lado esquerdo do cabeçalho do Diário Oficial. Recomendado: 60x60px', null=True, upload_to='diario_oficial/', verbose_name='Logo Esquerda (BR)')),
                ('texto_logo_esquerda', models.CharField(default='BR', help_text='Texto que aparece se não houver imagem (padrão: BR)', max_length=10, verbose_name='Texto Logo Esquerda')),
                ('logo_direita', models.ImageField(blank=True, help_text='Imagem que aparece no lado direito do cabeçalho do Diário Oficial. Recomendado: 60x60px', null=True, upload_to='diario_oficial/', verbose_name='Logo Direita (RP)')),
                ('texto_logo_direita', models.CharField(default='RP', help_text='Texto que aparece se não houver imagem (padrão: RP)', max_length=10, verbose_name='Texto Logo Direita')),
                ('titulo_diario', models.CharField(default='DIÁRIO OFICIAL DA UNIÃO', max_length=100, verbose_name='Título do Diário')),
                ('subtitulo_diario', models.CharField(default='REPÚBLICA FEDERATIVA DO BRASIL - IMPRENSA NACIONAL', max_length=200, verbose_name='Subtítulo do Diário')),
            ],
            options={
                'verbose_name': 'Configuração do Diário Oficial',
                'verbose_name_plural': 'Configurações do Diário Oficial',
            },
        ),
    ]
