# Generated by Django 4.2.7 on 2025-06-17 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_configuracaodiariooficial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticiaCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Classe do Ícone"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="NoticiaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="noticias/galeria/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Imagem de Notícia",
                "verbose_name_plural": "Imagens de Notícias",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="NoticiaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="noticia",
            options={
                "ordering": ["-data_publicacao", "-data_criacao"],
                "permissions": [
                    ("pode_publicar_noticias", "Pode publicar notícias"),
                    (
                        "pode_editar_noticias_outros",
                        "Pode editar notícias de outros autores",
                    ),
                    ("pode_moderar_noticias", "Pode moderar notícias"),
                ],
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
            },
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="imagem",
        ),
        migrations.AddField(
            model_name="noticia",
            name="conteudo_html",
            field=models.TextField(blank=True, verbose_name="Conteúdo HTML"),
        ),
        migrations.AddField(
            model_name="noticia",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noticias_editadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Editor",
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="fonte",
            field=models.CharField(blank=True, max_length=200, verbose_name="Fonte"),
        ),
        migrations.AddField(
            model_name="noticia",
            name="imagem_principal",
            field=models.ImageField(
                blank=True,
                help_text="Imagem principal da notícia, exibida no topo",
                null=True,
                upload_to="noticias/principais/",
                verbose_name="Imagem Principal",
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="link_fonte",
            field=models.URLField(blank=True, verbose_name="Link da Fonte"),
        ),
        migrations.AddField(
            model_name="noticia",
            name="permitir_comentarios",
            field=models.BooleanField(
                default=True, verbose_name="Permitir Comentários"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("revisao", "Em Revisão"),
                    ("publicado", "Publicado"),
                    ("arquivado", "Arquivado"),
                ],
                default="rascunho",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="NoticiaComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Comentário")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="main.noticia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="noticia",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, to="main.noticiacategoria", verbose_name="Categorias"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="galeria_imagens",
            field=models.ManyToManyField(
                blank=True,
                related_name="noticias",
                to="main.noticiaimagem",
                verbose_name="Galeria de Imagens",
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="main.noticiatag", verbose_name="Tags"
            ),
        ),
    ]
