# Generated by Django 4.2.7 on 2025-06-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_noticiacategoria_noticiaimagem_noticiatag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="resumo",
            field=models.TextField(blank=True, max_length=300, verbose_name="Resumo"),
        ),
    ]
