# Generated by Django 4.2.7 on 2025-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_make_resumo_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgao",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="orgao",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="orgao",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo oficial do órgão. Recomendado: 200x200px",
                null=True,
                upload_to="orgaos/logos/",
                verbose_name="Logo do Órgão",
            ),
        ),
        migrations.AddField(
            model_name="orgao",
            name="site_oficial",
            field=models.URLField(blank=True, verbose_name="Site Oficial"),
        ),
    ]
