# Generated by Django 4.2.7 on 2025-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_add_orgao_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="orgao_publicacao",
            field=models.CharField(
                blank=True,
                help_text="Nome do órgão do autor no momento da publicação (campo estático)",
                max_length=200,
                verbose_name="Órgão na Publicação",
            ),
        ),
    ]
