# Generated by Django 4.2.7 on 2025-06-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_noticialike"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publicacaodiariooficial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("historico_cargo__isnull", False)),
                fields=("historico_cargo", "tipo"),
                name="unique_publicacao_historico_tipo",
            ),
        ),
    ]
