# Generated by Django 4.2.7 on 2025-06-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_sistema_cidadania"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecieDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Espécie"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Espécie de Documento",
                "verbose_name_plural": "Espécies de Documentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Protocolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_protocolo",
                    models.CharField(
                        help_text="Formato: XX.XXX.XXX-X",
                        max_length=20,
                        unique=True,
                        verbose_name="Número do Protocolo",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                (
                    "detalhamento",
                    models.TextField(
                        help_text="Máximo 2.400 caracteres",
                        max_length=2400,
                        verbose_name="Detalhamento",
                    ),
                ),
                (
                    "urgencia",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="nao",
                        max_length=3,
                        verbose_name="Urgência",
                    ),
                ),
                (
                    "restricao_acesso",
                    models.CharField(
                        choices=[
                            ("publico", "Público"),
                            ("restrito", "Restrito"),
                            ("sigiloso", "Sigiloso"),
                        ],
                        default="publico",
                        max_length=10,
                        verbose_name="Restrição de Acesso",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizado", "Finalizado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="aberto",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "monitorado_por_usuario",
                    models.BooleanField(
                        default=False, verbose_name="Monitorado pelo Usuário"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "entidade_cadastro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos_cadastrados",
                        to="main.entidade",
                        verbose_name="Setor de Cadastro",
                    ),
                ),
                (
                    "entidade_destinatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos_recebidos",
                        to="main.entidade",
                        verbose_name="Setor Destinatário",
                    ),
                ),
                (
                    "especie_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.especiedocumento",
                        verbose_name="Espécie de Documento",
                    ),
                ),
                (
                    "orgao_cadastro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos_cadastrados",
                        to="main.orgao",
                        verbose_name="Órgão de Cadastro",
                    ),
                ),
                (
                    "orgao_destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos_recebidos",
                        to="main.orgao",
                        verbose_name="Órgão Destinatário",
                    ),
                ),
                (
                    "usuario_cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Cadastro",
                    ),
                ),
                (
                    "usuario_destinatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocolos_recebidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário Específico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocolo",
                "verbose_name_plural": "Protocolos",
                "ordering": ["-data_cadastro"],
                "permissions": [
                    ("pode_gerenciar_protocolos", "Pode gerenciar protocolos"),
                    ("pode_assinar_documentos", "Pode assinar documentos"),
                    ("pode_encaminhar_protocolos", "Pode encaminhar protocolos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtocoloDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Documento"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="protocolos/documentos/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("documento", "Documento"),
                            ("anexo", "Anexo"),
                            ("parecer", "Parecer"),
                        ],
                        default="documento",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "assinado",
                    models.BooleanField(default=False, verbose_name="Assinado"),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="main.protocolo",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "usuario_assinatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_assinados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Assinou",
                    ),
                ),
                (
                    "usuario_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que fez Upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Protocolo",
                "verbose_name_plural": "Documentos do Protocolo",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mensagem",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem opcional para o destinatário",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aceita", "Aceita"),
                            ("recusada", "Recusada"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_resposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "motivo_recusa",
                    models.TextField(
                        blank=True,
                        help_text="Obrigatório em caso de recusa",
                        verbose_name="Motivo da Recusa",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_assinatura",
                        to="main.protocolodocumento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "usuario_destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_assinatura_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Destinatário",
                    ),
                ),
                (
                    "usuario_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_assinatura_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Assinatura",
                "verbose_name_plural": "Solicitações de Assinatura",
                "ordering": ["-data_solicitacao"],
            },
        ),
        migrations.CreateModel(
            name="ProtocoloEncaminhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parecer", models.TextField(verbose_name="Parecer")),
                (
                    "data_encaminhamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Encaminhamento"
                    ),
                ),
                (
                    "entidade_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos_recebidos",
                        to="main.entidade",
                        verbose_name="Setor de Destino",
                    ),
                ),
                (
                    "entidade_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos_enviados",
                        to="main.entidade",
                        verbose_name="Setor de Origem",
                    ),
                ),
                (
                    "orgao_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos_recebidos",
                        to="main.orgao",
                        verbose_name="Órgão de Destino",
                    ),
                ),
                (
                    "orgao_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos_enviados",
                        to="main.orgao",
                        verbose_name="Órgão de Origem",
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos",
                        to="main.protocolo",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "usuario_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_recebidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Destino",
                    ),
                ),
                (
                    "usuario_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos_enviados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaminhamento de Protocolo",
                "verbose_name_plural": "Encaminhamentos de Protocolos",
                "ordering": ["-data_encaminhamento"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justificativa", models.TextField(verbose_name="Justificativa")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("negada", "Negada"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_resposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações do analista",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_acesso",
                        to="main.protocolo",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "usuario_analise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_acesso_analisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Analisou",
                    ),
                ),
                (
                    "usuario_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_acesso_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Acesso",
                "verbose_name_plural": "Solicitações de Acesso",
                "ordering": ["-data_solicitacao"],
                "unique_together": {("protocolo", "usuario_solicitante")},
            },
        ),
        migrations.CreateModel(
            name="ProtocoloInteressado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inclusao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Inclusão"
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.entidade",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "protocolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interessados",
                        to="main.protocolo",
                        verbose_name="Protocolo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Interessado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interessado no Protocolo",
                "verbose_name_plural": "Interessados no Protocolo",
                "unique_together": {("protocolo", "usuario")},
            },
        ),
    ]
