# Generated by Django 4.2.7 on 2025-06-19 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_sistema_protocolos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocoloencaminhamento",
            options={
                "ordering": ["-data_encaminhamento"],
                "verbose_name": "Encaminhamento de Protocolo",
                "verbose_name_plural": "Encaminhamentos de Protocolo",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacaoacesso",
            options={
                "ordering": ["-data_solicitacao"],
                "verbose_name": "Solicitação de Acesso ao Protocolo",
                "verbose_name_plural": "Solicitações de Acesso ao Protocolo",
            },
        ),
        migrations.RemoveField(
            model_name="solicitacaoacesso",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="solicitacaoacesso",
            name="usuario_analise",
        ),
        migrations.AddField(
            model_name="protocolodocumento",
            name="observacoes_assinatura",
            field=models.TextField(
                blank=True,
                help_text="Observações opcionais sobre a assinatura",
                verbose_name="Observações da Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoacesso",
            name="observacoes_resposta",
            field=models.TextField(blank=True, verbose_name="Observações da Resposta"),
        ),
        migrations.AddField(
            model_name="solicitacaoacesso",
            name="usuario_resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respostas_acesso_protocolo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Respondeu",
            ),
        ),
        migrations.AlterField(
            model_name="protocoloencaminhamento",
            name="entidade_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encaminhamentos_recebidos",
                to="main.entidade",
                verbose_name="Entidade de Destino",
            ),
        ),
        migrations.AlterField(
            model_name="protocoloencaminhamento",
            name="entidade_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encaminhamentos_enviados",
                to="main.entidade",
                verbose_name="Entidade de Origem",
            ),
        ),
        migrations.AlterField(
            model_name="protocoloencaminhamento",
            name="usuario_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encaminhamentos_recebidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Destinatário",
            ),
        ),
        migrations.AlterField(
            model_name="protocoloencaminhamento",
            name="usuario_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Encaminhou",
            ),
        ),
        migrations.AlterField(
            model_name="protocolointeressado",
            name="entidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.entidade",
                verbose_name="Setor do Interessado",
            ),
        ),
        migrations.AlterField(
            model_name="protocolointeressado",
            name="orgao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.orgao",
                verbose_name="Órgão do Interessado",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoacesso",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovada", "Aprovada"),
                    ("rejeitada", "Rejeitada"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoacesso",
            name="usuario_solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_acesso_protocolo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Solicitante",
            ),
        ),
    ]
