# Generated by Django 4.2.7 on 2025-06-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_add_observacoes_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolodocumento",
            name="identificador",
            field=models.CharField(
                blank=True,
                help_text="Identificador único do documento no protocolo (ex: DOC-001)",
                max_length=20,
                verbose_name="Identificador",
            ),
        ),
    ]
