# Generated by Django 5.2.4 on 2025-07-12 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_add_identificador_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações opcionais sobre a assinatura",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Se false, a assinatura foi revogada",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "cargo_assinante",
                    models.CharField(
                        blank=True,
                        help_text="Cargo do usuário no momento da assinatura",
                        max_length=200,
                        verbose_name="Cargo do Assinante",
                    ),
                ),
                (
                    "hash_documento",
                    models.CharField(
                        blank=True,
                        help_text="Hash do documento no momento da assinatura para validação",
                        max_length=64,
                        verbose_name="Hash do Documento",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas_multiplas",
                        to="main.protocolodocumento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Assinou",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de Documento",
                "verbose_name_plural": "Assinaturas de Documentos",
                "ordering": ["-data_assinatura"],
                "unique_together": {("documento", "usuario")},
            },
        ),
    ]
